### ISSUE TITLE
Mer fleksibel håndtering av csv fil

### ISSUE THREAD

**Issue by rannveigskjerve** [navikt/tms-brannslukning#24]
CSV opplastinga knekker veldig fort ved uventede mellomrom etc. Når det blir store mengder data kan det være lurt om det kan håndteres på en bedre måte (bedre feilhåndtering etc)
```[tasklist]
### Tasks
- [ ] Forbedre logging på hvorfor det feiler
- [ ] Ikke tolk som double
- [ ] Ikke tving bruker til å restarte hele prosessen dersom det feiler.
- [ ] Forklare bruker hvorfor det feiler
- [ ] Håndter byte-order-mark i fil
```
